language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - sudo add-apt-repository -y ppa:juju/stable
  - sudo apt-get update
  - sudo apt-get install juju-core bzr
install: "pip install -e .; pip install -r test-requires.txt; pip install python-coveralls"
script: "nosetests --nologcapture --with-coverage --cover-package=amulet -e functional"
after_success:
  - coveralls
